# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(1300, 800)
        Home.setMinimumSize(QtCore.QSize(1300, 800))
        Home.setMaximumSize(QtCore.QSize(1300, 800))
        Home.setStyleSheet("QMainWindow{\n"
"    border-image: url(:/bagru/main.png);\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.but_decode = QtWidgets.QPushButton(self.centralwidget)
        self.but_decode.setGeometry(QtCore.QRect(200, 460, 330, 130))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.but_decode.setFont(font)
        self.but_decode.setStyleSheet("background: rgb(234, 234, 234)")
        self.but_decode.setObjectName("but_decode")
        self.but_encode = QtWidgets.QPushButton(self.centralwidget)
        self.but_encode.setGeometry(QtCore.QRect(770, 460, 330, 130))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.but_encode.setFont(font)
        self.but_encode.setStyleSheet("background: rgb(234, 234, 234)")
        self.but_encode.setObjectName("but_encode")
        Home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 26))
        self.menubar.setObjectName("menubar")
        Home.setMenuBar(self.menubar)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Steganography"))
        self.but_decode.setText(_translate("Home", "DECODE"))
        self.but_encode.setText(_translate("Home", "ENCODE"))
import backgr_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())
